### ISSUE TITLE
testers must use the scope=tester

### ISSUE THREAD

**Issue by vanlooverenkoen** [vanlooverenkoen/flutter_appcenter_release_manager#18]
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: AppCenter Release Manager Error with message:

------------------------

Failed with 400 & body: {"code":"bad_request","message":"Error: Testers must use use the scope=tester parameter"}

------------------------

Instance of 'AppCenterApiError'
#0      Webservice.get (package:appcenter_release_manager/src/webservice/webservice.dart:23:7)
<asynchronous suspension>
#1      AppCenterRepository.getReleases (package:appcenter_release_manager/src/repo/appcenter_repository.dart:46:18)
<asynchronous suspension>
#2      _AppDetailState._getApps (package:appcenter_release_manager_example/main.dart:310:9)
<asynchronous suspension>
```

**Comment by vanlooverenkoen** [comment]
Because this plugin was initially developed with an admin account it was not possible to see or download apps when using a member or collaborator account. Or even if you were a tester that was invited to a single app.

How to fix this:

`/v0.1/apps` -> `/v0.1/tester/apps`
`/v0.1/apps/{owner_name}/{app_name}/releases` -> `/v0.1/apps/{owner_name}/{app_name}/releases?scope=testers`
